### ISSUE TITLE
Some artists and albums not showing 

### ISSUE THREAD

**Issue by jim4067** [qms-apps/eon-player-issue-tracker#59]
Hey 👋. Love the app. It seems that after the latest update some of my albums and artists are not showing up. I've tried rescannong but didn't solve anything. I even moved all the music files and folders into one parent directory but the same issue persists.

**Comment by qijaz221** [comment]
Hi, do they show up in any other player? Like stock music app on your device for example?

**Comment by jim4067** [comment]
oh no! it seems that its not available there also. Guess i'll be closing the issue :rocket:
